### ISSUE TITLE
Pyyaml is missing from requirements.txt

### ISSUE THREAD

**Issue by StEvUgnIn** [Luxembourg-Open-Source-Club/BICS-BOT#44]
# Describe the bug
``import yaml`` is not provided by current requirements.txt. yaml doesn't come by default on python >= 3.9

# To Reproduce
1. Create a new virtual environment
2. Install all dependencies from requirements.txt
3. Run the script
4. See error ModuleNotFoundError

# Expected behavior

It should run with any faulty behaviour instead.

# Log (if available):
```
Traceback (most recent call last):
  File "C:\Users\stevu\.conda\envs\lux-osc\lib\site-packages\nextcord\ext\commands\bot.py", line 765, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\bics_bot\cogs\commands\calendar_cmd.py", line 5, in <module>
    from bics_bot.utils.channels_utils import (
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\bics_bot\utils\channels_utils.py", line 5, in <module>
    from bics_bot.utils.server_utilities import retrieve_server_ids
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\bics_bot\utils\server_utilities.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

# Additional context
Configuration:
- Windows 11 x64
- Miniconda (conda version 23.9.0)
- python==3.9.18
- pip==23.2.1

**Comment by StEvUgnIn** [comment]
Assign it to me asap

**Comment by PedroS235** [comment]
Hey @StEvUgnIn . Actually, it's my bad. Need to merge the dev branch.

**Comment by PedroS235** [comment]
Wull merge asap

**Comment by StEvUgnIn** [comment]
Okay great, no bother. You can assign yourself then.
