### ISSUE TITLE
Flexible working directory

### ISSUE THREAD

**Issue by StEvUgnIn** [Luxembourg-Open-Source-Club/BICS-BOT#46]
# Describe the bug
Please read the following https://en.wikipedia.org/wiki/Working_directory

The current implementation assumes that CWD is defined as the root of the repository.

# To Reproduce
1. Provide a different path
2. Execute main.py from the different path
3. See the error that paths cannot be resolved

# Expected behavior
The backend application should work everywhere and not be tied to a work directory.

# Log (if available):
```shell
Traceback (most recent call last):
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\main.py", line 75, in <module>
    main()
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\main.py", line 66, in main
    description=read_txt("./bics_bot/texts/bot_description.txt"),
  File "c:\Users\stevu\git\Luxembourg-Open-Source-Club\BICS-BOT\src\bics_bot\utils\file_manipulation.py", line 14, in read_txt
    with open(path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: './bics_bot/texts/bot_description.txt'
```

**Comment by StEvUgnIn** [comment]
To assign to me ASAP
